#include "sort.hpp"
#include "../builtin_traits/iterator.hpp"

using namespace sy;

Result<void, ProgramError> sy::sortIntoSlice(IteratorObj* iter, void* outBuf, size_t outBufElemSize) noexcept {
    (void)outBuf;
    (void)outBufElemSize;
    const Type* valueType = iter->traitImpl->valueType;
    const Type* itemType = iter->traitImpl->item;
    // The iterator is yielding pointers but we want the underlying value
    const bool needsDeref = itemType != valueType;
    (void)needsDeref;

    //! DO NOT copy the iterator
    //! DO NOT allocate unnecessary memory
    //! DO NOT use templates, unless you match on the type, as this must work with types generated by the Sync compiler

    //! DO call valueType->copyConstructObj()
    //! DO call valueType->compareObj()
    //! DO call iter->next() in a loop

    /*
    When sorting:
        1. if needsDeref,
            then pass the pointers DIRECTLY, to the comparison function in valueType->compareObj().
        2. if not needsDeref,
            then pass pointers to the yielded item to the comparison function in valueType->compareObj().
    */

    return {}; // no error happened!
}
