//! API
#pragma once
#ifndef SY_PROGRAM_PROGRAM_ERROR_H_
#define SY_PROGRAM_PROGRAM_ERROR_H_

enum SyProgramError {
    /// This NONE variant means no error happened.
    SY_PROGRAM_ERROR_NONE = 0,
    SY_PROGRAM_ERROR_UNKNOWN = 1,
    SY_PROGRAM_ERROR_OUT_OF_MEMORY = 2,
    SY_PROGRAM_ERROR_COMPILE_SOURCE_FILE_TOO_BIG = 3,
    SY_PROGRAM_ERROR_COMPILE_NEGATIVE_TO_UNSIGNED_INT_CONVERSION = 4,
    SY_PROGRAM_ERROR_COMPILE_UNSIGNED_OUTSIDE_INT_RANGE_CONVERSION = 5,
    SY_PROGRAM_ERROR_COMPILE_FLOAT_OUTSIDE_INT_RANGE_CONVERSION = 6,
    SY_PROGRAM_ERROR_COMPILE_DECIMAL_NUMBER_LITERAL = 7,
    SY_PROGRAM_ERROR_COMPILE_CHAR_NUMBER_LITERAL = 8,
    SY_PROGRAM_ERROR_COMPILE_TOO_MANY_CHARS_IN_CHAR_LITERAL = 9,
    SY_PROGRAM_ERROR_COMPILE_UNSUPPORTED_CHAR = 10,
    SY_PROGRAM_ERROR_COMPILE_ESCAPE_SEQUENCE = 11,
    SY_PROGRAM_ERROR_COMPILE_FUNCTION_SIGNATURE = 12,
    SY_PROGRAM_ERROR_COMPILE_FUNCTION_STATEMENT = 13,
    SY_PROGRAM_ERROR_COMPILE_EXPRESSION = 14,
    SY_PROGRAM_ERROR_COMPILE_STATEMENT = 15,
    SY_PROGRAM_ERROR_COMPILE_SYMBOL = 16,
    SY_PROGRAM_ERROR_COMPILE_CIRCULAR_MODULE_DEPENDENCY = 17,
    SY_PROGRAM_ERROR_COMPILE_MODULE_DEPENDENCY_GRAPH = 18,
    SY_PROGRAM_ERROR_COMPILE_SELF_IMPORT = 19,
    SY_PROGRAM_ERROR_COMPILE_UNKNOWN_TYPE = 20,
    SY_PROGRAM_ERROR_BUFFER_TOO_SMALL = 21,
    SY_PROGRAM_ERROR_GEN_REF_STALE = 22,
};

#endif // SY_PROGRAM_PROGRAM_ERROR_H_
