name: "Mac Arm"

on:
    workflow_dispatch:
    workflow_call:

jobs:
  mac-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: lukka/get-cmake@latest 
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSYNC_LIB_DOCTEST_ADD_CTESTS=OFF
    - name: Build
      run: cmake --build build --config Debug --parallel
    - name: Test
      run: ./build/SyncLibTests