name: "Cross Platform Test"

on:
    workflow_dispatch:

jobs:
  ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: lukka/get-cmake@latest 
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSYNC_LIB_DOCTEST_ADD_CTESTS=OFF
    - name: Build
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build --output-on-failure