name: "Cross Platform Test"

on:
    workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: lukka/get-cmake@latest 
    - name: Configure CMake
      run: cmake -S ./lib/test -B lib/test/build -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: cmake --build lib/test/build --config Debug --parallel 
    - name: Executable Permissions
      run: chmod +x ./lib/test/build/Example
    - name: List Build Dir
      run: ls lib/test/build
    - name: Test
      run: ./lib/test/build/Example

  ubuntu-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: lukka/get-cmake@latest 
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSYNC_LIB_DOCTEST_ADD_CTESTS=OFF
    - name: Build
      run: cmake --build build --config Debug --parallel
    - name: Executable Permissions
      run: chmod +x ./build/SyncLibTests
    - name: List Build Dir
      run: ls build
    - name: Test
      run: ./build/SyncLibTests
  
# jobs:
#   ubuntu-x64:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build
#       run: g++ lib/test/example.cpp -o example
#     - name: Permissions
#       run: chmod +x example
#     - name: Test
#       run: ./example

      #cmake -S ./lib/test -B lib/test/build -DCMAKE_BUILD_TYPE=Debug
      #cmake --build lib/test/build --config Debug --parallel  