name: "Ubuntu Arm"

on:
    workflow_dispatch:

jobs:
  ubuntu-arm:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      uses: lukka/get-cmake@latest 
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DSYNC_LIB_DOCTEST_ADD_CTESTS=OFF
    - name: Build
      run: cmake --build build --config Debug --parallel
    - name: Executable Permissions
      run: chmod +x ./build/SyncLibTests
    - name: Test
      run: ./build/SyncLibTests
